// components/Footer.vue
<script setup lang="ts">
import {version} from '../package.json'
</script>

<template>
  <footer class="shrink-0 h-6">
    <div class="text-center text-xs font-light">
      {{ version }} | Star on
      <a href="https://github.com/Jazee6/cloudflare-ai-web" target="_blank"
         class="text-neutral-500 hover:text-neutral-900 underline dark:text-neutral-400 dark:hover:text-neutral-300">GitHub</a>
    </div>
  </footer>
</template>

// components/footer.tsx
import { cn } from "@/lib/utils";
import { version } from "@/package.json";

const Footer = ({ classname }: { classname?: string }) => {
  return (
    <footer
      className={cn(
        classname,
        "text-muted-foreground *:[a]:hover:text-primary text-center text-xs text-balance *:[a]:underline *:[a]:underline-offset-4",
      )}
    >
      {version} | Star on{" "}
      <a
        href="https://github.com/Jazee6/cloudflare-ai-web"
        target="_blank"
        rel="noopener"
      >
        Github
      </a>
    </footer>
  );
};

export default Footer;
